name: resizer
description: "Image reize tool"
publish_to: 'none'
version: 0.1.0

environment:
  sdk: ^3.10.7

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  file_picker: ^10.3.8
  package_info_plus: ^9.0.0
  path: ^1.9.1
  font_awesome_flutter: ^10.12.0
  ffi: ^2.1.5
  window_manager: ^0.5.1
  desktop_drop: ^0.7.0
  shared_preferences: ^2.5.4
  url_launcher: ^6.3.2
  get: ^4.7.3
  dropdown_button2: ^2.3.9
  msix: ^3.16.13

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0

flutter:
  uses-material-design: true
  fonts:
    - family: "PuHui"
      fonts:
        - asset: font/AlibabaPuHuiTi-3-Regular.ttf
  assets:
    - assets/

msix_config:
  display_name: Resizer App
  publisher_display_name: ZhouCheng
  identity_name: ZhouCheng.ResizerApp
  msix_version: 0.1.0.0
  logo_path: assets/icon.png
  trim_logo: false
  capabilities: internetClient
  languages: zh-cn, en-us, zh-tw
  publisher: # Publisher
  store: true